services:
  customer-service:
    image: objectworld/customer-service:0.0.1-SNAPSHOT
    ports:
      - "8080"
    networks:
      - shopping-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
  product-service:
    image: objectworld/product-service:0.0.1-SNAPSHOT
    ports:
      - "8080"
    networks:
      - shopping-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
  order-service:
    image: objectworld/order-service:0.0.1-SNAPSHOT
    ports:
      - "8080"
    networks:
      - shopping-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
networks:
  shopping-net:
    name: shopping
    external: true