server:
  port: 0
spring:
  config:
    import: optional:configserver:http://config-service:8788
    activate:
      on-profile: docker
---
spring:
  application:
    name: product-service  
  config:
    import: optional:configserver:http://localhost:8788